export const siteUrl = "https://www.themetricapp.com";
export const siteName = "TheMetricApp";
export const siteDescription =
  "Free financial calculators and business tools for freelancers, gig workers, sellers, and self-employed professionals. Calculate taxes, fees, profits, savings, and ROI with fast, accurate 2026 guidance.";
export const authorName = "TheMetricApp Team";
export const siteKeywords = [
  "financial calculators",
  "tax calculator",
  "gig economy taxes",
  "e-commerce profit calculator",
  "self employment tax",
  "freelancer tools",
  "small business calculators",
  "startup finance tools",
];

export const navLinks = [
  { href: "/", label: "Home" },
  { href: "/blog", label: "Blog" },
  { href: "/faq", label: "FAQ" },
  { href: "/about", label: "About Us" },
  { href: "/contact", label: "Contact" },
];

export const calculators = [
  // NEW CALCULATORS — June 22, 2026
  {
    href: "/calculators/ebay-fee-calculator",
    title: "eBay Fee Calculator",
    desc: "Calculate eBay final value fees and your net profit on every sale. Category-specific UK & US rates, checked for 2026.",
    icon: "🏷️",
    tag: "Marketplace",
  },
  {
    href: "/calculators/amazon-fba-calculator",
    title: "Amazon FBA Calculator",
    desc: "Estimate Amazon referral fees, FBA fulfilment fees, net profit and ROI for UK and US sellers. Rates checked for 2026.",
    icon: "📦",
    tag: "Marketplace",
  },
  // NEW CALCULATORS — July 4, 2026: marketplace & creator cluster (shown first under "New")
  {
    href: "/calculators/poshmark-fee-calculator",
    title: "Poshmark Fee Calculator",
    desc: "See exactly what Poshmark takes — $2.95 flat under $15 or 20% commission — and your true payout and profit on every sale.",
    icon: "👗",
    tag: "New",
  },
  {
    href: "/calculators/mercari-fee-calculator",
    title: "Mercari Fee Calculator",
    desc: "Calculate Mercari's flat 10% selling fee (no processing charge since 2025) and your exact payout and profit on any sale.",
    icon: "🛍️",
    tag: "New",
  },
  {
    href: "/calculators/depop-fee-calculator",
    title: "Depop Fee Calculator",
    desc: "Depop dropped its US selling fee — just 3.3% + $0.45 processing (plus optional 12% boost). See your exact payout.",
    icon: "🧥",
    tag: "New",
  },
  {
    href: "/calculators/whatnot-fee-calculator",
    title: "Whatnot Fee Calculator",
    desc: "Live selling fees decoded: 8% commission + 2.9% + $0.30 processing. See your true payout per sale and per stream.",
    icon: "📺",
    tag: "New",
  },
  {
    href: "/calculators/stockx-fee-calculator",
    title: "StockX Fee Calculator",
    desc: "StockX seller fees by level (8–9.5% + 3% processing), shipping bonuses, and your true payout on sneakers and collectibles.",
    icon: "👟",
    tag: "New",
  },
  {
    href: "/calculators/facebook-marketplace-fee-calculator",
    title: "Facebook Marketplace Fee Calculator",
    desc: "Shipped orders pay 10% ($0.80 min); local pickup is free. Compare both and see your exact payout.",
    icon: "🏪",
    tag: "New",
  },
  {
    href: "/calculators/onlyfans-tax-calculator",
    title: "OnlyFans Tax Calculator",
    desc: "Estimate SE tax, federal tax, and quarterly payments on OnlyFans income — with the 20% platform fee deducted correctly.",
    icon: "📱",
    tag: "New",
  },
  {
    href: "/calculators/creator-tax-calculator",
    title: "Content Creator Tax Calculator",
    desc: "YouTube, Twitch, TikTok, and sponsorship income — estimate SE tax, federal tax, and what to set aside quarterly.",
    icon: "🎬",
    tag: "New",
  },
  {
    href: "/calculators/turo-profit-calculator",
    title: "Turo Profit Calculator",
    desc: "Estimate real Turo host income — 70/80/90% earnings plan share minus car payment and running costs, monthly and annually.",
    icon: "🚗",
    tag: "New",
  },
  {
    href: "/calculators/instacart-tax-calculator",
    title: "Instacart Tax Calculator",
    desc: "Shopper taxes with the $0.725/mile deduction and the new OBBBA tips deduction for delivery drivers. Includes quarterly amounts.",
    icon: "🛒",
    tag: "New",
  },
  // July 4, 2026 — OBBBA cluster (moved from "New" to real categories)
  {
    href: "/calculators/no-tax-on-tips-calculator-2026",
    title: "No Tax on Tips Calculator",
    desc: "Estimate your federal tax savings from the OBBBA $25,000 qualified tips deduction for 2026. W-2 and self-employed tipped workers, with phase-out limits.",
    icon: "💵",
    tag: "Tax Tools",
  },
  {
    href: "/calculators/car-loan-interest-deduction-calculator-2026",
    title: "Car Loan Interest Deduction Calculator",
    desc: "Estimate your OBBBA tax savings — deduct up to $10,000 of interest on new US-assembled vehicles, with real amortization math and phase-outs.",
    icon: "🚙",
    tag: "Auto & Loans",
  },
  {
    href: "/calculators/senior-tax-deduction-calculator-2026",
    title: "Senior Tax Deduction Calculator",
    desc: "Estimate the $6,000 OBBBA bonus deduction for age 65+ ($12,000 for couples), the 6% phase-out, and your total tax-free income for 2026.",
    icon: "👴",
    tag: "Retirement",
  },
  {
    href: "/calculators/social-security-tax-calculator",
    title: "Social Security Tax Calculator",
    desc: "Find how much of your Social Security benefits are taxable under the IRS 0%, 50%, and 85% combined-income rules with exact worksheet math.",
    icon: "🧓",
    tag: "Retirement",
  },
  {
    href: "/calculators/obbba-tax-savings-calculator",
    title: "OBBBA Tax Savings Calculator",
    desc: "Stack all four One Big Beautiful Bill deductions — tips, overtime, senior bonus, and car loan interest — and see your total 2026 savings.",
    icon: "🏛️",
    tag: "Tax Tools",
  },
  // June 13, 2026 calculators (moved from "New" to their real categories)
  {
    href: "/calculators/no-tax-on-overtime-calculator-2026",
    title: "No Tax on Overtime Calculator",
    desc: "Estimate your federal income tax savings on overtime pay under the OBBBA deduction for 2026. W-2 employees only, with phase-out limits.",
    icon: "⏱️",
    tag: "Tax Tools",
  },
  {
    href: "/calculators/freelancer-platform-fee-calculator-2026",
    title: "Freelancer Platform Fee Calculator",
    desc: "Compare your real take-home pay after Fiverr, Upwork, Toptal, Contra, and PeoplePerHour fees. Free 2026 freelancer fee comparison.",
    icon: "💼",
    tag: "Freelancing",
  },
  {
    href: "/calculators/break-even-calculator-small-business",
    title: "Break-Even Calculator",
    desc: "Find how many units you need to sell to cover fixed and variable costs, with contribution margin analysis for small business and e-commerce.",
    icon: "⚖️",
    tag: "Self-Employment",
  },
  {
    href: "/calculators/tiktok-shop-earnings-calculator-2026",
    title: "TikTok Shop Earnings Calculator",
    desc: "Estimate your net TikTok Shop earnings after referral fees, affiliate commissions, COGS, and shipping. Built for TikTok sellers and creators.",
    icon: "🎵",
    tag: "E-Commerce",
  },
  {
    href: "/calculators/w2-vs-1099-calculator-2026",
    title: "W-2 vs 1099 Calculator",
    desc: "Compare your real take-home pay as a W-2 employee versus a 1099 independent contractor. Includes SE tax, QBI, benefits value, and break-even rate.",
    icon: "🧾",
    tag: "Tax Tools",
  },
  {
    href: "/calculators/doordash-tax-estimator",
    title: "DoorDash Tax Estimator",
    desc: "Estimate self-employment taxes, mileage deductions, and quarterly payments for DoorDash drivers.",
    icon: "🚗",
    tag: "Gig Economy",
  },
  {
    href: "/calculators/texas-paycheck-calculator",
    title: "Texas Paycheck Calculator",
    desc: "Calculate take-home pay in Texas after federal withholding, FICA, and benefits deductions.",
    icon: "🤠",
    tag: "Paycheck",
  },
  {
    href: "/calculators/california-1099-tax-calculator",
    title: "California 1099 Tax Calculator",
    desc: "Compute federal and California self-employment taxes for 1099 contractors and freelancers.",
    icon: "☀️",
    tag: "Self-Employment",
  },
  {
    href: "/calculators/stripe-fee-merchant-calculator",
    title: "Stripe Fee Calculator",
    desc: "See how Stripe fees affect your gross revenue and net payout for every transaction.",
    icon: "💳",
    tag: "Merchant Fees",
  },
  {
    href: "/calculators/ecommerce-net-profit-margin",
    title: "E-Commerce Profit Margin",
    desc: "Calculate gross profit, net profit, margin percentage, and ROI for online sales.",
    icon: "📦",
    tag: "E-Commerce",
  },
  {
    href: "/calculators/freelancer-platform-fee-comparison",
    title: "Freelancer Fee Comparison",
    desc: "Compare Upwork, Fiverr, and other freelancer platform fees to maximize net earnings.",
    icon: "💼",
    tag: "Freelancing",
  },
  {
    href: "/calculators/ev-charging-vs-gas-savings",
    title: "EV vs Gas Savings",
    desc: "Compare total ownership costs to see whether electric vehicles or gas cars are cheaper.",
    icon: "⚡",
    tag: "Automotive",
  },
  {
    href: "/calculators/residential-solar-panel-roi",
    title: "Solar Panel ROI",
    desc: "Estimate payback period, savings, and return on investment for residential solar.",
    icon: "🌞",
    tag: "Energy",
  },
  {
    href: "/calculators/ebay-seller-fee-profit",
    title: "eBay Seller Fee & Profit",
    desc: "Calculate eBay seller fees, net profit, and true cost per sale for every listing.",
    icon: "🏷️",
    tag: "Marketplace",
  },
  {
    href: "/calculators/airbnb-host-net-income",
    title: "Airbnb Host Net Income",
    desc: "Estimate your Airbnb profits after fees, occupancy taxes, and operating expenses.",
    icon: "🏠",
    tag: "Real Estate",
  },
  {
    href: "/calculators/rental-property-roi-calculator",
    title: "Rental Property ROI Calculator",
    desc: "Calculate cap rate, cash-on-cash return, NOI, DSCR, and the 1% rule for any rental property.",
    icon: "📊",
    tag: "Real Estate",
  },
  {
    href: "/calculators/us-import-tariff-calculator",
    title: "US Import Tariff Calculator",
    desc: "Calculate import duties, fees, and landed cost for products coming into the U.S.",
    icon: "🛃",
    tag: "Import & Trade",
  },
  {
    href: "/calculators/side-hustle-tax-calculator",
    title: "Side Hustle Tax Calculator",
    desc: "Estimate self-employment tax, federal income tax, and quarterly payments for gig income.",
    icon: "💰",
    tag: "Gig Economy",
  },
  {
    href: "/calculators/irs-mileage-deduction-calculator",
    title: "IRS Mileage Deduction Calculator",
    desc: "Calculate federal mileage deductions for business, medical, and charity driving.",
    icon: "🚗",
    tag: "Tax Deductions",
  },
  {
    href: "/calculators/solo-401k-contribution-calculator",
    title: "Solo 401k Contribution Calculator",
    desc: "Find the maximum Solo 401k contribution and tax savings for self-employed professionals.",
    icon: "🏦",
    tag: "Retirement",
  },
  {
    href: "/calculators/paypal-fee-calculator",
    title: "PayPal Fee Calculator",
    desc: "Compare PayPal fees, net payout, and invoice costs to keep more of every sale.",
    icon: "💳",
    tag: "Merchant Fees",
  },
  {
    href: "/calculators/vat-calculator-uk",
    title: "VAT Calculator UK",
    desc: "Add or remove 20% VAT instantly. Calculate net, gross, and VAT amounts for UK businesses and freelancers.",
    icon: "🇬🇧",
    tag: "Tax Tools",
  },
  {
    href: "/calculators/income-tax-calculator-uk",
    title: "Income Tax Calculator UK",
    desc: "Calculate UK Income Tax, National Insurance, and take-home pay for 2026/27. Accurate HMRC PAYE rates, instant results.",
    icon: "🇬🇧",
    tag: "Tax Tools",
  },
  {
    href: "/calculators/national-insurance-calculator-uk",
    title: "National Insurance Calculator UK",
    desc: "Work out Class 1, 2 and 4 National Insurance for 2026/27 — employee, self-employed, and employer NI in seconds. Free HMRC-rate tool.",
    icon: "🇬🇧",
    tag: "Tax Tools",
  },
  {
    href: "/calculators/self-assessment-tax-calculator-uk",
    title: "Self Assessment Tax Calculator UK",
    desc: "Estimate your 2026/27 Self Assessment bill — Income Tax, Class 4 NI, and payments on account for sole traders and freelancers.",
    icon: "🧾",
    tag: "Tax Tools",
  },
  {
    href: "/calculators/mortgage-calculator-uk",
    title: "Mortgage Calculator UK",
    desc: "Calculate monthly UK mortgage repayments, total interest, and stamp duty. Compare repayment vs interest-only in seconds.",
    icon: "🏠",
    tag: "Real Estate",
  },
  {
    href: "/calculators/hourly-to-annual-salary-calculator-uk",
    title: "Hourly to Annual Salary Calculator UK",
    desc: "Convert your hourly rate to annual salary instantly. Includes standard hours, overtime, and statutory holiday pay for 2026/27.",
    icon: "💷",
    tag: "Tax Tools",
  },
  {
    href: "/calculators/capital-gains-tax-calculator",
    title: "Capital Gains Tax Calculator",
    desc: "Calculate your 2026 capital gains tax liability. Estimate short-term and long-term gains taxes with federal brackets, NIIT, and state tax adjustments.",
    icon: "💰",
    tag: "Tax Tools",
  },
  // NEW CALCULATORS — added May 2026
  {
    href: "/calculators/uber-tax-calculator-2026",
    title: "Uber Tax Calculator",
    desc: "Estimate self-employment taxes, mileage deductions, and quarterly payments for Uber drivers and rideshare workers.",
    icon: "🚗",
    tag: "Gig Economy",
  },
  {
    href: "/calculators/new-york-paycheck-calculator-2026",
    title: "New York Paycheck Calculator",
    desc: "Calculate take-home pay in New York after federal withholding, FICA, and NY state income tax deductions.",
    icon: "🗽",
    tag: "Paycheck",
  },
  {
    href: "/calculators/florida-paycheck-calculator-2026",
    title: "Florida Paycheck Calculator",
    desc: "Calculate take-home pay in Florida after federal withholding and FICA — zero state income tax!",
    icon: "🌴",
    tag: "Paycheck",
  },
  {
    href: "/calculators/etsy-fee-calculator-2026",
    title: "Etsy Fee Calculator",
    desc: "Calculate Etsy seller fees including listing fees, transaction fees, and payment processing costs.",
    icon: "🧶",
    tag: "Marketplace",
  },
  {
    href: "/calculators/shopify-profit-calculator-2026",
    title: "Shopify Profit Calculator",
    desc: "Calculate Shopify store profits after subscription fees, transaction fees, COGS, and marketing costs.",
    icon: "🛒",
    tag: "E-Commerce",
  },
  {
    href: "/calculators/self-employment-tax-calculator-2026",
    title: "Self Employment Tax Calculator",
    desc: "Calculate your self-employment tax (15.3%) with Social Security and Medicare portions for 1099 workers.",
    icon: "💼",
    tag: "Self-Employment",
  },
  {
    href: "/calculators/home-affordability-calculator-2026",
    title: "Home Affordability Calculator",
    desc: "Calculate how much house you can afford based on income, down payment, debts, and interest rates.",
    icon: "🏡",
    tag: "Real Estate",
  },
  {
    href: "/calculators/dividend-tax-calculator-2026",
    title: "Dividend Tax Calculator",
    desc: "Calculate taxes on qualified and ordinary dividends with federal brackets, NIIT, and state tax.",
    icon: "📈",
    tag: "Tax Tools",
  },
  {
    href: "/calculators/amazon-seller-fee-calculator-2026",
    title: "Amazon Seller Fee Calculator",
    desc: "Calculate Amazon FBM referral fees, closing fees, and net profit for marketplace sellers.",
    icon: "📦",
    tag: "Marketplace",
  },
  {
    href: "/calculators/crypto-tax-calculator-2026",
    title: "Crypto Tax Calculator",
    desc: "Calculate cryptocurrency capital gains taxes for short-term and long-term Bitcoin, Ethereum, and altcoin trades.",
    icon: "₿",
    tag: "Tax Tools",
  },
  {
    href: "/calculators/small-business-tax-deduction-calculator",
    title: "Small Business Tax Deduction Calculator",
    desc: "Calculate your small business tax deductions, self-employment tax, QBI deduction, and quarterly estimated payments for 2026.",
    icon: "💼",
    tag: "Self-Employment",
  },
  {
    href: "/calculators/gig-economy-net-income-calculator",
    title: "Gig Economy Net Income Calculator",
    desc: "Calculate your actual take-home pay after mileage deductions, expenses, and self-employment taxes for Uber, DoorDash, Instacart, and more.",
    icon: "🚗",
    tag: "Gig Economy",
  },
  {
    href: "/calculators/credit-card-payoff-calculator",
    title: "Credit Card Payoff Calculator",
    desc: "Compare snowball vs avalanche debt payoff methods. Add multiple cards and see how extra payments save you thousands in interest.",
    icon: "💳",
    tag: "Debt Payoff",
  },
  {
    href: "/calculators/student-loan-payoff-calculator",
    title: "Student Loan Payoff Calculator",
    desc: "Calculate student loan payments, total interest, and payoff timeline. See how extra payments save you money on federal and private loans.",
    icon: "🎓",
    tag: "Debt Payoff",
  },
  // NEW CALCULATORS — Phase 3 May 2026
  {
    href: "/calculators/car-loan-affordability-calculator-2026",
    title: "Car Loan Affordability Calculator",
    desc: "Calculate monthly car payments, total interest, and whether a car fits your budget with DTI analysis and total cost of ownership.",
    icon: "🚘",
    tag: "Auto & Loans",
  },
  {
    href: "/calculators/retirement-savings-calculator-2026",
    title: "Retirement Savings Calculator",
    desc: "Project your retirement savings growth, monthly income using the 4% rule, and income replacement rate. Free 2026 retirement planner.",
    icon: "🏦",
    tag: "Retirement",
  },
  // NEW CALCULATORS — Phase 4 May 2026
  {
    href: "/calculators/college-savings-calculator-2026",
    title: "College Savings Calculator",
    desc: "Project 529 plan growth, estimate college costs, calculate state tax deductions, and find your monthly savings target to fund your child's education.",
    icon: "🎓",
    tag: "Savings & Education",
  },
  {
    href: "/calculators/roth-vs-traditional-ira-calculator-2026",
    title: "Roth vs Traditional IRA Calculator",
    desc: "Compare Roth IRA vs Traditional IRA side-by-side. Calculate after-tax values at retirement and see which account type saves you more.",
    icon: "🏦",
    tag: "Retirement",
  },
  // NEW CALCULATORS — Phase 5 May 2026
  {
    href: "/calculators/emergency-fund-calculator",
    title: "Emergency Fund Calculator",
    desc: "Calculate your emergency fund target based on monthly expenses, income stability, and current savings. Free 2026 emergency savings calculator with personalized recommendations.",
    icon: "🆘",
    tag: "Personal Finance",
  },
  {
    href: "/calculators/net-worth-calculator",
    title: "Net Worth Calculator",
    desc: "Calculate your net worth by adding up all assets and liabilities. Free 2026 net worth tracker with asset allocation analysis and debt-to-asset ratio.",
    icon: "📊",
    tag: "Personal Finance",
  },
  // NEW CALCULATORS — Phase 5 Day 2 May 2026
  {
    href: "/calculators/mortgage-refinance-calculator-2026",
    title: "Mortgage Refinance Calculator",
    desc: "Calculate savings, break-even point, and total interest saved when refinancing your mortgage. Free 2026 mortgage refi calculator with monthly payment comparison and closing costs.",
    icon: "🏠",
    tag: "Real Estate",
  },
  {
    href: "/calculators/loan-comparison-calculator",
    title: "Loan Comparison Calculator",
    desc: "Compare two loans side-by-side with monthly payment, total interest, APR, and total cost. Free 2026 loan comparison calculator for auto, personal, and student loans.",
    icon: "💰",
    tag: "Loans",
  },
  // NEW CALCULATORS — Day 3 May 2026
  {
    href: "/calculators/savings-goal-calculator",
    title: "Savings Goal Calculator",
    desc: "Project how your savings grow over time with regular contributions and compound interest. Free 2026 savings goal calculator for retirement, down payment, education, and any financial goal.",
    icon: "🎯",
    tag: "Savings & Planning",
  },
  {
    href: "/calculators/inflation-calculator",
    title: "Inflation Calculator",
    desc: "Calculate how inflation reduces the purchasing power of your money over time. Free 2026 inflation calculator with year-by-year projections and multiple rate scenarios.",
    icon: "📈",
    tag: "Savings & Planning",
  },
  // NEW CALCULATORS — Day 4 May 2026
  {
    href: "/calculators/cost-of-living-calculator",
    title: "Cost of Living Calculator",
    desc: "Compare the cost of living between two cities based on salary, housing, groceries, utilities, transportation, and more. Free 2026 cost of living comparison tool with salary adjustment.",
    icon: "🏙️",
    tag: "Personal Finance",
  },
  {
    href: "/calculators/commission-calculator",
    title: "Commission Calculator",
    desc: "Calculate commission earnings based on sale amount, commission rate, tiers, splits, and bonuses. Free 2026 commission calculator for sales professionals, real estate agents, and reps.",
    icon: "💼",
    tag: "Personal Finance",
  },
  // NEW CALCULATORS — June 2026 Batch
  {
    href: "/calculators/401k-retirement-calculator",
    title: "401(k) Retirement Calculator",
    desc: "Project your 401(k) growth with employer match, catch-up contributions, and compound interest. Free 2026 401(k) retirement calculator for employees.",
    icon: "🏦",
    tag: "Retirement",
  },
  {
    href: "/calculators/budget-calculator",
    title: "Budget Calculator",
    desc: "Create a personal budget with income, fixed expenses, variable expenses, and savings goals. Free 2026 budget calculator with 50/30/20 rule.",
    icon: "📋",
    tag: "Personal Finance",
  },
  {
    href: "/calculators/mortgage-calculator-us",
    title: "Mortgage Calculator US",
    desc: "Calculate monthly mortgage payments with principal, interest, taxes, insurance, and PMI. Free 2026 US mortgage calculator with amortization table.",
    icon: "🏡",
    tag: "Real Estate",
  },
  {
    href: "/calculators/roth-ira-growth-calculator",
    title: "Roth IRA Growth Calculator",
    desc: "Project your Roth IRA growth with annual contributions, compound interest, and tax-free withdrawals. Free 2026 Roth IRA growth calculator.",
    icon: "📈",
    tag: "Retirement",
  },
  {
    href: "/calculators/amortization-calculator",
    title: "Amortization Calculator",
    desc: "Generate a full amortization schedule showing monthly payment breakdown into principal and interest. Free 2026 loan amortization calculator.",
    icon: "📊",
    tag: "Loans",
  },
  {
    href: "/calculators/hourly-wage-calculator-us",
    title: "Hourly Wage Calculator US",
    desc: "Convert hourly wage to annual salary, monthly pay, and weekly pay for US workers. Includes overtime, time-and-a-half, and double-time calculations.",
    icon: "💵",
    tag: "Paycheck",
  },
  {
    href: "/calculators/dti-ratio-calculator",
    title: "DTI Ratio Calculator",
    desc: "Calculate your debt-to-income ratio used by lenders for mortgage, auto, and personal loan approvals. Free 2026 DTI ratio calculator with front-end and back-end ratios.",
    icon: "📉",
    tag: "Loans",
  },
];

export const blogPosts = [
  {
    slug: "capital-gains-tax-calculator-2026",
    title: "Capital Gains Tax Calculator 2026: Complete Guide to Short-Term & Long-Term Gain Taxes",
    excerpt:
      "Master capital gains taxes in 2026. Learn how to calculate short-term and long-term gains, NIIT surcharge, state taxes, tax-loss harvesting strategies, and real-world examples with step-by-step math.",
    date: "May 27, 2026",
    author: "TheMetricApp Team",
    readTime: "12 min read",
    category: "Investment Tax",
    tags: ["Capital Gains", "Investment Tax", "Tax-Loss Harvesting", "NIIT", "Long-Term Gains"],
  },
  {
    slug: "rental-property-roi-calculator-2026",
    title: "Rental Property ROI Calculator 2026: Cap Rate, Cash-on-Cash Return & NOI Guide",
    excerpt:
      "Master rental property ROI analysis in 2026. Learn how to calculate cap rate, cash-on-cash return, NOI, DSCR, and use the 1% rule to find profitable investment properties.",
    date: "May 27, 2026",
    author: "TheMetricApp Team",
    readTime: "12 min read",
    category: "Real Estate Investing",
    tags: ["Rental Property", "ROI", "Cap Rate", "Real Estate Investing", "Cash Flow"],
  },
  {
    slug: "amazon-fba-fee-calculator-2026",
    title: "Amazon FBA Fee Calculator 2026: Complete Guide to Selling Fees & Net Profit",
    excerpt:
      "Learn how to calculate Amazon FBA fees in 2026. Complete guide to referral fees, fulfillment fees, the new 3.5% fuel surcharge, storage costs, and strategies to maximize your Amazon selling profit.",
    date: "May 27, 2026",
    author: "TheMetricApp Team",
    readTime: "12 min read",
    category: "E-Commerce",
    tags: ["Amazon FBA", "Fulfillment Fees", "Referral Fees", "E-Commerce", "Amazon Seller"],
  },
  {
    slug: "hourly-to-annual-salary-calculator-uk-2026",
    title: "Hourly to Annual Salary Calculator UK 2026: Complete Guide & Free Tool",
    excerpt:
      "Free hourly to annual salary calculator UK 2026 guide. Convert your hourly wage to yearly pay instantly. Includes standard hours, overtime, holiday pay, and HMRC compliance for UK workers.",
    date: "May 26, 2026",
    author: "TheMetricApp Team",
    readTime: "10 min read",
    category: "Salary & Payroll",
    tags: ["Hourly Wage", "Salary", "UK", "Overtime", "HMRC", "Payroll"],
  },
  {
    slug: "us-import-tariff-calculator-2026",
    title: "US Import Tariff Calculator 2026: Duties, Landed Cost & Section 232 Guide",
    excerpt:
      "Free US import tariff calculator for 2026. Calculate duties at 20% China, 10% Vietnam, 3.5% UK/EU rates. Includes Section 232 surcharges, MPF, HMF and total landed cost. Essential for Amazon FBA and e-commerce importers.",
    date: "May 25, 2026",
    author: "TheMetricApp Team",
    readTime: "12 min read",
    category: "Import & Trade",
    tags: ["Import", "Tariff", "E-Commerce", "Amazon FBA", "International Trade"],
  },
  {
    slug: "side-hustle-tax-calculator-2026",
    title: "Side Hustle Tax Calculator 2026: Gig Income, SE Tax & Quarterly Payments Guide",
    excerpt:
      "Free side hustle tax calculator for 2026. Calculate self-employment tax, federal income tax, state tax, and quarterly estimated payments for Uber, DoorDash, Fiverr, Etsy and Airbnb income.",
    date: "May 25, 2026",
    author: "TheMetricApp Team",
    readTime: "12 min read",
    category: "Gig Economy",
    tags: ["Side Hustle", "Gig Economy", "Self-Employment", "Taxes", "Freelancing"],
  },
  {
    slug: "irs-mileage-deduction-calculator-2026",
    title: "IRS Mileage Deduction Calculator 2026: $0.725/Mile Tax Savings Guide",
    excerpt:
      "Free IRS mileage deduction calculator for 2026. Calculate your deduction at $0.725/mile for business, $0.205/mile for medical, and $0.14/mile for charity. Includes standard mileage vs actual expenses comparison.",
    date: "May 25, 2026",
    author: "TheMetricApp Team",
    readTime: "10 min read",
    category: "Tax Deductions",
    tags: ["Mileage Deduction", "IRS", "Tax Savings", "Gig Workers", "Self-Employment"],
  },
  {
    slug: "solo-401k-contribution-calculator-2026",
    title: "Solo 401k Contribution Limits 2026: Complete Guide to Maxing Out Retirement Savings",
    excerpt:
      "Complete guide to Solo 401k contributions in 2026. Learn the $70,000 limit, SECURE 2.0 super catch-up for ages 60-63, employer profit-sharing, and tax savings strategies for freelancers and self-employed.",
    date: "May 25, 2026",
    author: "TheMetricApp Team",
    readTime: "12 min read",
    category: "Retirement Planning",
    tags: ["Retirement", "Solo 401k", "Self-Employment", "Tax Savings", "Freelancing"],
  },
  {
    slug: "paypal-fee-calculator-2026",
    title: "PayPal Fee Calculator 2026: Complete Guide to Fees, Rates & Savings",
    excerpt:
      "Complete guide to PayPal fees in 2026. Calculate exact costs for goods and services, invoices, international transactions, and micropayments. Compare PayPal vs Stripe and learn how to reduce fees.",
    date: "May 25, 2026",
    author: "TheMetricApp Team",
    readTime: "12 min read",
    category: "Payment Processing",
    tags: ["PayPal", "Payment Processing", "Fees", "Stripe", "E-Commerce"],
  },
  {
    slug: "texas-paycheck-calculator-2026",
    title: "Texas Paycheck Calculator 2026: Take-Home Pay After Federal & State Withholding",
    excerpt:
      "Texas may have no state income tax, but federal withholdings, FICA, and benefits deductions still take a bite. Learn exactly how to calculate your net paycheck in 2026 with real formulas and examples.",
    date: "May 25, 2026",
    author: "TheMetricApp Team",
    readTime: "10 min read",
    category: "Paycheck",
    tags: ["Texas", "Paycheck", "Payroll", "Withholding", "Salary"],
  },
  {
    slug: "airbnb-host-net-income-2026",
    title: "Airbnb Host Net Income Calculator 2026: Maximize Your Short-Term Rental Profit",
    excerpt:
      "Discover how to calculate your true Airbnb host net income in 2026 — factoring in cleaning fees, service charges, occupancy taxes, mortgage costs, and seasonal demand shifts for US and UK hosts.",
    date: "May 25, 2026",
    author: "TheMetricApp Team",
    readTime: "11 min read",
    category: "Real Estate",
    tags: ["Airbnb", "Short-Term Rental", "Host Income", "Vacation Rental", "Real Estate"],
  },
  {
    slug: "residential-solar-panel-roi-2026",
    title: "Residential Solar Panel ROI Calculator 2026: Is Solar Worth It in Your State?",
    excerpt:
      "With the 30% federal tax credit, net metering policies, and rising electricity rates, solar has never more compelling. Calculate your solar ROI, payback period, and 25-year savings in 2026.",
    date: "May 25, 2026",
    author: "TheMetricApp Team",
    readTime: "11 min read",
    category: "Energy Savings",
    tags: ["Solar", "ROI", "Energy", "Incentives", "Renewable"],
  },
  {
    slug: "ev-charging-vs-gas-savings-2026",
    title: "EV vs Gas Savings Calculator 2026: True Cost of Ownership in the US & UK",
    excerpt:
      "Should you switch to an electric vehicle in 2026? Compare total cost of ownership across charging costs, fuel prices, maintenance, insurance, and government incentives for EV and gas cars in the US and UK.",
    date: "May 25, 2026",
    author: "TheMetricApp Team",
    readTime: "10 min read",
    category: "Automotive",
    tags: ["EV", "Electric Vehicle", "Gas Savings", "TCO", "Green"],
  },
  {
    slug: "freelancer-platform-fee-comparison-2026",
    title: "Freelancer Platform Fee Comparison 2026: Upwork, Fiverr & Toptal Net Earnings",
    excerpt:
      "Compare the real cost of freelancing on Upwork, Fiverr, Toptal, and Freelancer.com in 2026. Learn how service fees, payment processing, and currency conversion affect your net earnings in the US and UK.",
    date: "May 25, 2026",
    author: "TheMetricApp Team",
    readTime: "10 min read",
    category: "Freelancing",
    tags: ["Freelancing", "Upwork", "Fiverr", "Toptal", "Platform Fees"],
  },
  {
    slug: "california-1099-tax-calculator-2026",
    title: "California 1099 Tax Calculator 2026: Complete Guide to Self-Employment & State Taxes",
    excerpt:
      "Living and working as a 1099 contractor in California means facing the highest combined tax burden in the US. Learn how to calculate your self-employment, federal, and CA state taxes with real 2026 formulas, examples, and expert strategies.",
    date: "May 21, 2026",
    author: "TheMetricApp Team",
    readTime: "10 min read",
    category: "Tax Tips",
    tags: ["California", "1099 Taxes", "Self-Employment", "Freelancing", "State Tax"],
  },
  {
    slug: "doordash-tax-estimator-2026",
    title: "DoorDash Tax Estimator 2026: Complete Guide to Self-Employment Taxes & Mileage Deductions",
    excerpt:
      "Everything DoorDash drivers need to know about taxes in 2026 — self-employment tax rates, the $0.725/mile mileage deduction, quarterly estimated payments, and US vs UK differences for gig workers.",
    date: "May 21, 2026",
    author: "TheMetricApp Team",
    readTime: "10 min read",
    category: "Gig Economy",
    tags: ["DoorDash", "Gig Economy", "Self-Employment", "Mileage Deduction", "1099"],
  },
  {
    slug: "stripe-fee-calculator-2026",
    title: "Stripe Fee Calculator 2026: Complete Guide to Processing Fees & Net Payouts",
    excerpt:
      "Everything you need to know about Stripe's 2026 fee structure — domestic and international rates, hidden fees, volume discounts, surcharging rules, and how to calculate your true net payout on every transaction.",
    date: "May 21, 2026",
    author: "TheMetricApp Team",
    readTime: "8 min read",
    category: "Merchant Fees",
    tags: ["Stripe", "Payment Processing", "Fees", "Merchant Account"],
  },
  {
    slug: "ebay-seller-fee-profit-2026",
    title: "eBay Seller Fee Calculator 2026: Master Final Value Fees, Net Profit & ROI",
    excerpt:
      "The complete guide to eBay selling fees in 2026 — understand final value fees, Managed Payments, promoted listings costs, and exactly how to calculate your true net profit on every item you sell.",
    date: "May 21, 2026",
    author: "TheMetricApp Team",
    readTime: "9 min read",
    category: "Marketplace Selling",
    tags: ["eBay", "Selling Fees", "Profit", "Reselling", "Marketplace"],
  },
  {
    slug: "ecommerce-profit-margin-calculator-2026",
    title: "E-Commerce Profit Margin Calculator 2026: Master Your Net Profit, ROAS & Break-Even",
    excerpt:
      "Learn exactly how to calculate your true e-commerce profitability in 2026 — whether you sell on Amazon, Shopify, eBay, or Etsy in the US or UK — with real formulas, examples, and expert tips.",
    date: "May 21, 2026",
    author: "TheMetricApp Team",
    readTime: "8 min read",
    category: "E-Commerce",
    tags: ["E-Commerce", "Profit Margin", "ROAS", "Amazon", "Shopify", "eBay"],
  },
  {
    slug: "self-employment-tax-tips-2026",
    title: "Self-Employment Tax Tips for 2026: What Every Freelancer Should Know",
    excerpt:
      "Tax season looks different when you're self-employed. From estimated quarterly payments to the home office deduction, here are the essential strategies to keep more of your hard-earned money this year.",
    date: "May 15, 2026",
    author: "TheMetricApp Team",
    readTime: "8 min read",
    category: "Tax Tips",
    tags: ["Self-Employment", "Taxes", "Freelancing"],
  },
  {
    slug: "stripe-vs-paypal-fees-2026",
    title: "Stripe vs PayPal Fees in 2026: Which Payment Processor Is Cheaper?",
    excerpt:
      "We break down the real cost of accepting payments with Stripe and PayPal — including hidden fees, international rates, and which platform saves you more at different transaction volumes.",
    date: "May 8, 2026",
    author: "TheMetricApp Team",
    readTime: "6 min read",
    category: "Merchant Fees",
    tags: ["Stripe", "PayPal", "Payment Processing"],
  },
  {
    slug: "is-solar-worth-it-2026",
    title: "Is Solar Power Worth It in 2026? Payback Periods Across the US",
    excerpt:
      "With the 30% federal tax credit locked in through 2032 and electricity rates rising nationwide, now might be the best time to go solar. We crunched the numbers for every state.",
    date: "April 28, 2026",
    author: "TheMetricApp Team",
    readTime: "10 min read",
    category: "Energy Savings",
    tags: ["Solar", "Energy", "ROI", "Incentives"],
  },
  {
    slug: "small-business-tax-deduction-calculator-2026",
    title: "Small Business Tax Deduction Calculator 2026: 25+ Write-Offs You're Missing",
    excerpt: "Complete guide to small business tax deductions for 2026. Learn about self-employment tax, QBI deduction, home office, mileage, retirement plans, and 25+ write-offs every business owner should know. Includes real examples and free calculator.",
    date: "May 28, 2026",
    author: "TheMetricApp Team",
    readTime: "12 min read",
    category: "Tax Tips",
    tags: ["Small Business", "Tax Deductions", "Self-Employment", "QBI", "Quarterly Taxes"],
  },
  {
    slug: "gig-economy-net-income-calculator-2026",
    title: "Gig Economy Net Income Calculator 2026: Uber, DoorDash, Instacart Take-Home Pay",
    excerpt: "Calculate your true hourly rate after mileage deductions, business expenses, and self-employment taxes for Uber, DoorDash, Instacart, and Lyft. Complete guide with real examples and free calculator.",
    date: "May 28, 2026",
    author: "TheMetricApp Team",
    readTime: "12 min read",
    category: "Gig Economy",
    tags: ["Gig Economy", "DoorDash", "Uber", "Net Income", "Self-Employment"],
  },
  {
    slug: "credit-card-payoff-calculator-2026",
    title: "Credit Card Payoff Calculator 2026: Snowball vs Avalanche Method Complete Guide",
    excerpt: "Compare snowball vs avalanche debt payoff methods with our free calculator. Add multiple cards and see exactly how extra payments save you thousands in interest. Complete guide with real examples.",
    date: "May 28, 2026",
    author: "TheMetricApp Team",
    readTime: "12 min read",
    category: "Debt Payoff",
    tags: ["Credit Card", "Debt Payoff", "Snowball Method", "Avalanche Method", "Personal Finance"],
  },
  {
    slug: "student-loan-payoff-calculator-2026",
    title: "Student Loan Payoff Calculator 2026: Complete Guide to Paying Off $30k-$100k Faster",
    excerpt: "Learn how to pay off student loans faster in 2026. Complete guide to federal rates, repayment plans, extra payment strategies, and PSLF. Free calculator to estimate savings.",
    date: "May 28, 2026",
    author: "TheMetricApp Team",
    readTime: "12 min read",
    category: "Debt Payoff",
    tags: ["Student Loans", "Debt Payoff", "Federal Loans", "PSLF", "Refinancing"],
  },
  {
    slug: "car-loan-affordability-calculator-2026",
    title: "Car Loan Affordability Calculator 2026: Complete Guide to Auto Loans, Payments & Budgeting",
    excerpt: "Learn how to calculate car loan affordability in 2026. Complete guide to monthly payments, DTI ratios, down payments, loan terms, and total cost of ownership. Free calculator included.",
    date: "May 29, 2026",
    author: "TheMetricApp Team",
    readTime: "12 min read",
    category: "Auto & Loans",
    tags: ["Car Loan", "Auto Financing", "Affordability", "DTI", "Car Buying"],
  },
  {    slug: "retirement-savings-calculator-2026",
    title: "Retirement Savings Calculator 2026: Complete Guide to the 4% Rule & Compound Growth",
    excerpt:
      "Master retirement planning in 2026. Learn how compound interest grows your savings, how the 4% safe withdrawal rule works, and how to calculate your income replacement rate. Free calculator included.",
    date: "May 29, 2026",
    author: "TheMetricApp Team",
    readTime: "12 min read",
    category: "Retirement Planning",
    tags: ["Retirement", "4% Rule", "Compound Interest", "Savings", "FIRE"],
  },
  {
    slug: "college-savings-calculator-2026",
    title: "College Savings Calculator 2026: Complete Guide to 529 Plans, Tuition Costs & Education Funding",
    excerpt:
      "Project your 529 plan growth, estimate tuition costs, calculate state tax deductions, and find the monthly savings target to fund your child's education. Free college savings calculator included.",
    date: "May 29, 2026",
    author: "TheMetricApp Team",
    readTime: "12 min read",
    category: "Savings & Education",
    tags: ["College Savings", "529 Plan", "Education Funding", "Tuition Costs", "State Tax Deductions"],
  },
  {
    slug: "roth-vs-traditional-ira-calculator-2026",
    title: "Roth vs Traditional IRA Calculator 2026: Complete Guide to Choosing the Right Account",
    excerpt:
      "Compare Roth IRA vs Traditional IRA side-by-side. Calculate after-tax values at retirement, tax savings, and find which account type saves you more. Free comparison calculator included.",
    date: "May 29, 2026",
    author: "TheMetricApp Team",
    readTime: "12 min read",
    category: "Retirement Planning",
    tags: ["Roth IRA", "Traditional IRA", "Retirement", "IRA Comparison", "Backdoor Roth"],
  },
  {
    slug: "emergency-fund-calculator",
    title: "Emergency Fund Calculator 2026: Complete Guide to Building Your Financial Safety Net",
    excerpt:
      "Free emergency fund calculator for 2026. Calculate how much you need based on monthly expenses and income stability. Includes income stability multipliers, savings strategies, and real examples.",
    date: "May 30, 2026",
    author: "TheMetricApp Team",
    readTime: "12 min read",
    category: "Personal Finance",
    tags: ["Emergency Fund", "Emergency Savings", "Personal Finance", "Financial Safety Net", "Savings"],
  },
  {
    slug: "net-worth-calculator",
    title: "Net Worth Calculator 2026: Complete Guide to Calculating & Improving Your Net Worth",
    excerpt:
      "Free net worth calculator for 2026. Calculate your total assets minus liabilities to find your financial net worth. Includes benchmarks by age, improvement strategies, and real examples.",
    date: "May 30, 2026",
    author: "TheMetricApp Team",
    readTime: "12 min read",
    category: "Personal Finance",
    tags: ["Net Worth", "Personal Finance", "Wealth Building", "Assets", "Financial Health"],
  },
  {
    slug: "mortgage-refinance-calculator-2026",
    title: "Mortgage Refinance Calculator 2026: Complete Guide to Refinancing Your Home Loan",
    excerpt:
      "Free mortgage refinance calculator for 2026. Calculate savings, break-even point, and total interest saved. Includes current rates, closing costs, and expert strategies.",
    date: "May 30, 2026",
    author: "TheMetricApp Team",
    readTime: "12 min read",
    category: "Real Estate",
    tags: ["Mortgage Refinance", "Refinancing", "Real Estate", "Mortgage Rates", "Home Loans"],
  },
  {
    slug: "loan-comparison-calculator",
    title: "Loan Comparison Calculator 2026: Complete Guide to Comparing Loans & APRs",
    excerpt:
      "Free loan comparison calculator for 2026. Compare two loans side-by-side with monthly payments, total interest, APR, and total cost. Includes auto, personal, and student loan strategies.",
    date: "May 30, 2026",
    author: "TheMetricApp Team",
    readTime: "12 min read",
    category: "Loans",
    tags: ["Loan Comparison", "APR", "Auto Loans", "Personal Loans", "Student Loans"],
  },
  {
    slug: "savings-goal-calculator",
    title: "Savings Goal Calculator 2026: Complete Guide to Compound Interest & Financial Planning",
    excerpt:
      "Free savings goal calculator for 2026. Learn how compound interest grows your money, how to set SMART savings goals, and strategies to reach $10k, $50k, $100k, and $1M milestones. Complete guide with real examples.",
    date: "May 30, 2026",
    author: "TheMetricApp Team",
    readTime: "12 min read",
    category: "Savings & Planning",
    tags: ["Savings Goal", "Compound Interest", "Personal Finance", "Goal Setting", "Savings Plan"],
  },
  {
    slug: "inflation-calculator",
    title: "Inflation Calculator 2026: Complete Guide to Purchasing Power & Protecting Your Savings",
    excerpt:
      "Free inflation calculator for 2026. Learn how inflation erodes your purchasing power, historical inflation data, the Rule of 70, and proven strategies to protect your savings from rising prices.",
    date: "May 30, 2026",
    author: "TheMetricApp Team",
    readTime: "12 min read",
    category: "Savings & Planning",
    tags: ["Inflation", "Purchasing Power", "CPI", "I Bonds", "TIPS", "Inflation Protection"],
  },
  {
    slug: "cost-of-living-calculator",
    title: "Cost of Living Calculator 2026: Complete Guide to Comparing Cities & Salary Adjustments",
    excerpt:
      "Free cost of living calculator for 2026. Compare housing, groceries, utilities, transportation, and healthcare costs between two cities. Includes salary adjustment calculations, COL index data, and relocation planning strategies.",
    date: "May 30, 2026",
    author: "TheMetricApp Team",
    readTime: "12 min read",
    category: "Personal Finance",
    tags: ["Cost of Living", "Relocation", "Salary Adjustment", "Housing", "City Comparison"],
  },
  {
    slug: "commission-calculator",
    title: "Commission Calculator 2026: Complete Guide to Sales Commission Structures & Earnings",
    excerpt:
      "Free commission calculator for 2026. Learn how to calculate commission earnings with tiered rates, splits, draws, and bonuses. Includes real estate, SaaS, car sales, and multi-level commission structures with real examples.",
    date: "May 30, 2026",
    author: "TheMetricApp Team",
    readTime: "12 min read",
    category: "Personal Finance",
    tags: ["Commission", "Sales", "Real Estate", "Commission Splits", "Commission Structures"],
  },
  {
    slug: "401k-retirement-calculator",
    title: "401(k) Retirement Calculator 2026: Complete Guide to Employer-Sponsored Retirement Plans",
    excerpt:
      "Master 401(k) retirement planning in 2026. Learn how employer matching works, catch-up contributions for ages 50+, the SECURE 2.0 super catch-up for ages 60-63, Roth 401(k) options, and how to maximize your tax-advantaged retirement savings.",
    date: "June 1, 2026",
    author: "TheMetricApp Team",
    readTime: "12 min read",
    category: "Retirement Planning",
    tags: ["401(k)", "Retirement", "Employer Match", "Catch-Up Contributions", "Roth 401(k)"],
  },
  {
    slug: "budget-calculator",
    title: "Budget Calculator 2026: Complete Guide to the 50/30/20 Rule & Personal Budgeting",
    excerpt:
      "Free budget calculator for 2026. Master the 50/30/20 budgeting rule, track fixed vs variable expenses, set savings goals, and build a personal budget that works. Includes real examples and expert strategies.",
    date: "June 1, 2026",
    author: "TheMetricApp Team",
    readTime: "12 min read",
    category: "Personal Finance",
    tags: ["Budget", "50/30/20 Rule", "Personal Finance", "Budgeting", "Savings Goals"],
  },
  {
    slug: "mortgage-calculator-us",
    title: "US Mortgage Calculator 2026: Complete Guide to Monthly Payments, PITI & Amortization",
    excerpt:
      "Free US mortgage calculator for 2026. Learn how PITI (Principal, Interest, Taxes, Insurance) works, how PMI affects your payment, and how to read an amortization table. Includes FHA, VA, and conventional loan comparisons.",
    date: "June 1, 2026",
    author: "TheMetricApp Team",
    readTime: "12 min read",
    category: "Real Estate",
    tags: ["Mortgage", "PITI", "PMI", "Home Buying", "Amortization", "FHA", "VA Loan", "Conventional Loan"],
  },
  {
    slug: "roth-ira-growth-calculator",
    title: "Roth IRA Growth Calculator 2026: Complete Guide to Tax-Free Retirement Growth",
    excerpt:
      "Free Roth IRA growth calculator for 2026. Learn how compound interest grows your Roth IRA tax-free, contribution limits, income phase-outs, and conversion strategies. Includes real examples from age 22 to retirement.",
    date: "June 1, 2026",
    author: "TheMetricApp Team",
    readTime: "12 min read",
    category: "Retirement Planning",
    tags: ["Roth IRA", "Retirement Growth", "Compound Interest", "Tax-Free", "IRA Conversions"],
  },
  {
    slug: "amortization-calculator",
    title: "Amortization Calculator 2026: Complete Guide to Loan Payment Schedules & Interest",
    excerpt:
      "Free amortization calculator for 2026. Learn how amortization schedules work, how front-loaded interest affects your loan, and strategies to pay off your mortgage, auto, or personal loan faster. Includes real examples.",
    date: "June 1, 2026",
    author: "TheMetricApp Team",
    readTime: "12 min read",
    category: "Loans",
    tags: ["Amortization", "Loan Schedule", "Interest", "Mortgage", "Principal Paydown"],
  },
  {
    slug: "hourly-wage-calculator-us",
    title: "Hourly Wage Calculator US 2026: Complete Guide to Annual Salary & Overtime Pay",
    excerpt:
      "Free hourly wage calculator for US workers in 2026. Convert hourly rate to annual salary, monthly pay, and weekly pay. Includes overtime at 1.5x and 2x rates, FLSA compliance, and salary negotiation tips.",
    date: "June 1, 2026",
    author: "TheMetricApp Team",
    readTime: "10 min read",
    category: "Paycheck & Salary",
    tags: ["Hourly Wage", "Salary Conversion", "Overtime", "FLSA", "Payroll", "US Labor Law"],
  },
  {
    slug: "dti-ratio-calculator",
    title: "DTI Ratio Calculator 2026: Complete Guide to Debt-to-Income Ratios for Loans",
    excerpt:
      "Free DTI ratio calculator for 2026. Learn how front-end and back-end DTI ratios work, what lenders look for in mortgage and auto loan approvals, and strategies to improve your debt-to-income ratio before applying.",
    date: "June 1, 2026",
    author: "TheMetricApp Team",
    readTime: "10 min read",
    category: "Loans & Credit",
    tags: ["DTI Ratio", "Debt-to-Income", "Mortgage Approval", "Credit", "Loan Approval"],
  },
  // NEW June 2026 — 9 Missing Blog Posts
  {
    slug: "amazon-seller-fee-calculator-2026",
    title: "Amazon Seller Fee Calculator 2026: Complete Guide to FBM Fees & Net Profit",
    excerpt: "Learn how to calculate Amazon FBM seller fees in 2026. Complete guide to referral fees, closing fees, COGS, shipping costs, and strategies to maximize your Amazon selling profit.",
    date: "June 1, 2026",
    author: "TheMetricApp Team",
    readTime: "12 min read",
    category: "E-Commerce",
    tags: ["Amazon", "FBM", "Fees", "E-Commerce", "Amazon Seller"],
  },
  {
    slug: "crypto-tax-calculator-2026",
    title: "Crypto Tax Calculator 2026: Complete Guide to Cryptocurrency Capital Gains",
    excerpt: "Learn how to calculate cryptocurrency capital gains taxes in 2026. Complete guide to short-term vs long-term crypto tax rates, tax-loss harvesting, and IRS reporting requirements.",
    date: "June 1, 2026",
    author: "TheMetricApp Team",
    readTime: "12 min read",
    category: "Cryptocurrency",
    tags: ["Crypto", "Capital Gains", "Cryptocurrency", "Tax", "IRS"],
  },
  {
    slug: "dividend-tax-calculator-2026",
    title: "Dividend Tax Calculator 2026: Complete Guide to Qualified & Ordinary Dividend Taxes",
    excerpt: "Learn how dividend taxes work in 2026. Complete guide to qualified vs ordinary dividend tax rates, NIIT surcharge, state taxes, and strategies to minimize your dividend tax burden.",
    date: "June 1, 2026",
    author: "TheMetricApp Team",
    readTime: "12 min read",
    category: "Investing",
    tags: ["Dividend", "Tax", "Qualified Dividends", "Investing", "NIIT"],
  },
  {
    slug: "etsy-fee-calculator-2026",
    title: "Etsy Fee Calculator 2026: Complete Guide to Seller Fees & Net Profit",
    excerpt: "Learn how to calculate Etsy seller fees in 2026. Complete guide to listing fees, transaction fees, payment processing, offsite ads, and strategies to maximize your Etsy shop profit.",
    date: "June 1, 2026",
    author: "TheMetricApp Team",
    readTime: "12 min read",
    category: "E-Commerce",
    tags: ["Etsy", "Fees", "Marketplace", "E-Commerce", "Seller"],
  },
  {
    slug: "florida-paycheck-calculator-2026",
    title: "Florida Paycheck Calculator 2026: Complete Guide to Take-Home Pay & Zero State Tax",
    excerpt: "Learn how to calculate your Florida take-home pay in 2026. Complete guide to federal taxes, FICA, pre-tax deductions, and why Florida's zero state income tax saves you thousands.",
    date: "June 1, 2026",
    author: "TheMetricApp Team",
    readTime: "10 min read",
    category: "Payroll",
    tags: ["Florida", "Paycheck", "Payroll", "Tax", "Take-Home Pay"],
  },
  {
    slug: "home-affordability-calculator-2026",
    title: "Home Affordability Calculator 2026: How Much House Can You Afford?",
    excerpt: "Learn how to calculate how much house you can afford in 2026. Complete guide to the 28/36 DTI rule, down payments, interest rates, and smart home buying strategies.",
    date: "June 1, 2026",
    author: "TheMetricApp Team",
    readTime: "12 min read",
    category: "Real Estate",
    tags: ["Home Affordability", "Mortgage", "DTI", "Real Estate", "Home Buying"],
  },
  {
    slug: "new-york-paycheck-calculator-2026",
    title: "New York Paycheck Calculator 2026: Complete Guide to Take-Home Pay & NY State Tax",
    excerpt: "Learn how to calculate your New York take-home pay in 2026. Complete guide to NY state income tax brackets, federal tax, FICA, NYC local tax, and paycheck optimization strategies.",
    date: "June 1, 2026",
    author: "TheMetricApp Team",
    readTime: "12 min read",
    category: "Payroll",
    tags: ["New York", "Paycheck", "Payroll", "State Tax", "NYC"],
  },
  {
    slug: "shopify-profit-calculator-2026",
    title: "Shopify Profit Calculator 2026: Complete Guide to Store Fees & Net Profit",
    excerpt: "Learn how to calculate your Shopify store profits in 2026. Complete guide to subscription plans, transaction fees, COGS, marketing costs, and strategies to maximize your e-commerce profitability.",
    date: "June 1, 2026",
    author: "TheMetricApp Team",
    readTime: "12 min read",
    category: "E-Commerce",
    tags: ["Shopify", "Profit", "E-Commerce", "Fees", "Online Store"],
  },
  {
    slug: "uber-tax-calculator-2026",
    title: "Uber Tax Calculator 2026: Complete Guide to Self-Employment Taxes & Mileage Deductions",
    excerpt: "Learn how Uber driver taxes work in 2026. Complete guide to self-employment tax, standard mileage deduction, quarterly estimated payments, and strategies to reduce your Uber tax burden.",
    date: "June 1, 2026",
    author: "TheMetricApp Team",
    readTime: "12 min read",
    category: "Gig Economy",
    tags: ["Uber", "Tax", "Gig Economy", "Mileage Deduction", "Self-Employment"],
  },
  // UK Blog Posts — missing from registration
  {
    slug: "mortgage-calculator-uk-2026",
    title: "Mortgage Calculator UK 2026: Complete Guide to Monthly Repayments, Stamp Duty & Affordability",
    excerpt: "Free mortgage calculator UK guide for 2026/27. Estimate monthly repayments, total interest, stamp duty costs, and borrowing affordability with real examples and expert tips for first-time buyers.",
    date: "May 26, 2026",
    author: "TheMetricApp Team",
    readTime: "12 min read",
    category: "Property",
    tags: ["Mortgage", "UK", "Stamp Duty", "First-Time Buyer", "Property"],
  },
  {
    slug: "national-insurance-calculator-uk-2026",
    title: "National Insurance Calculator UK 2026: Complete Guide to Class 1, 2 & 4 NI Contributions",
    excerpt: "Free UK National Insurance calculator guide for 2026/27. Calculate Class 1 employee NI, Class 4 self-employed NI, and employer NI contributions. Accurate HMRC rates, instant results.",
    date: "May 26, 2026",
    author: "TheMetricApp Team",
    readTime: "10 min read",
    category: "Tax Tools",
    tags: ["National Insurance", "UK", "NI", "HMRC", "Self-Employment"],
  },
  {
    slug: "self-assessment-tax-calculator-uk-2026",
    title: "Self Assessment Tax Calculator UK 2026: Complete Guide to Tax Returns, NI & Payments on Account",
    excerpt: "Free Self Assessment tax calculator UK guide for 2026/27. Estimate your tax bill, Class 4 NI, and payments on account. Accurate HMRC rates for sole traders and freelancers.",
    date: "May 26, 2026",
    author: "TheMetricApp Team",
    readTime: "10 min read",
    category: "Tax Tools",
    tags: ["Self Assessment", "UK", "Tax Return", "HMRC", "Sole Trader", "Freelancing"],
  },
  {
    slug: "income-tax-calculator-uk-2026",
    title: "Income Tax Calculator UK 2026: Complete Guide to PAYE, NI & Take-Home Pay",
    excerpt: "Free UK Income Tax calculator guide for 2026/27. Estimate your PAYE, National Insurance, and true take-home pay. Accurate HMRC rates, real examples, and tax-saving strategies.",
    date: "May 26, 2026",
    author: "TheMetricApp Team",
    readTime: "10 min read",
    category: "Tax Tools",
    tags: ["Income Tax", "UK", "PAYE", "HMRC", "Take-Home Pay", "Salary"],
  },
  {
    slug: "vat-calculator-uk-2026",
    title: "VAT Calculator UK 2026: Complete Guide to Adding, Removing & Managing VAT",
    excerpt: "Free VAT calculator UK guide for 2026/27. Add or remove 20% VAT instantly. Covers registration thresholds, Flat Rate Scheme, and MTD compliance for UK businesses.",
    date: "May 26, 2026",
    author: "TheMetricApp Team",
    readTime: "10 min read",
    category: "Tax Tools",
    tags: ["VAT", "UK", "HMRC", "MTD", "Small Business", "Freelancing"],
  },
  // NEW BLOG POSTS — June 13, 2026 (companions to the 5 new calculators)
  {
    slug: "no-tax-on-overtime-calculator-2026",
    title: "No Tax on Overtime Calculator 2026: Complete Guide to the OBBBA Deduction",
    excerpt: "Complete 2026 guide to the no tax on overtime rule under the OBBBA. Learn how the overtime tax deduction works, who qualifies, phase-out limits, and how to estimate your federal tax savings.",
    date: "June 13, 2026",
    author: "TheMetricApp Team",
    readTime: "10 min read",
    category: "Tax Tips",
    tags: ["Overtime", "OBBBA", "Tax Deduction", "W-2", "Federal Tax"],
  },
  {
    slug: "freelancer-platform-fee-calculator-2026",
    title: "Freelancer Platform Fee Calculator 2026: Fiverr vs Upwork vs Toptal vs Contra",
    excerpt: "Compare freelancer platform fees in 2026 across Fiverr, Upwork, Toptal, Contra, and PeoplePerHour. Learn how each fee works and how to keep more of your take-home pay.",
    date: "June 13, 2026",
    author: "TheMetricApp Team",
    readTime: "10 min read",
    category: "Freelancing",
    tags: ["Freelancing", "Fiverr", "Upwork", "Toptal", "Platform Fees"],
  },
  {
    slug: "break-even-calculator-small-business",
    title: "Break-Even Calculator Guide 2026: Units, Revenue & Contribution Margin",
    excerpt: "Complete 2026 guide to break-even analysis for small business and e-commerce. Learn the break-even formula, contribution margin, and how many units you must sell to profit.",
    date: "June 13, 2026",
    author: "TheMetricApp Team",
    readTime: "11 min read",
    category: "E-Commerce",
    tags: ["Break-Even", "Contribution Margin", "Small Business", "E-Commerce", "Pricing"],
  },
  {
    slug: "tiktok-shop-earnings-calculator-2026",
    title: "TikTok Shop Earnings Calculator 2026: Fees, Commissions & Net Profit",
    excerpt: "Complete 2026 guide to TikTok Shop seller fees. Learn referral fees by category, affiliate commissions, and how to calculate your true net profit per sale.",
    date: "June 13, 2026",
    author: "TheMetricApp Team",
    readTime: "11 min read",
    category: "Marketplace Selling",
    tags: ["TikTok Shop", "Seller Fees", "Affiliate", "E-Commerce", "Net Profit"],
  },
  {
    slug: "w2-vs-1099-calculator-2026",
    title: "W-2 vs 1099 Calculator 2026: Employee vs Contractor Take-Home Pay",
    excerpt: "Complete 2026 guide to W-2 vs 1099. Learn the real tax difference, self-employment tax, QBI, the break-even contractor rate, and when 1099 makes more financial sense.",
    date: "June 13, 2026",
    author: "TheMetricApp Team",
    readTime: "12 min read",
    category: "Tax Tips",
    tags: ["W-2", "1099", "Self-Employment", "QBI", "Contractor"],
  },
];

export const footerColumns = [
  {
    title: "Tax Tools",
    links: [
      { title: "California 1099 Tax", href: "/calculators/california-1099-tax-calculator" },
      { title: "DoorDash Driver Tax", href: "/calculators/doordash-tax-estimator" },
      { title: "Side Hustle Tax", href: "/calculators/side-hustle-tax-calculator" },
      { title: "Texas Paycheck", href: "/calculators/texas-paycheck-calculator" },
      { title: "IRS Mileage Deduction", href: "/calculators/irs-mileage-deduction-calculator" },
      { title: "VAT Calculator UK", href: "/calculators/vat-calculator-uk" },
      { title: "Income Tax Calculator UK", href: "/calculators/income-tax-calculator-uk" },
      { title: "Hourly to Annual Salary UK", href: "/calculators/hourly-to-annual-salary-calculator-uk" },
      { title: "Capital Gains Tax", href: "/calculators/capital-gains-tax-calculator" },
      { title: "Self Employment Tax", href: "/calculators/self-employment-tax-calculator-2026" },
      { title: "Dividend Tax", href: "/calculators/dividend-tax-calculator-2026" },
      { title: "Crypto Tax", href: "/calculators/crypto-tax-calculator-2026" },
      { title: "Home Affordability", href: "/calculators/home-affordability-calculator-2026" },
      { title: "Car Loan Affordability", href: "/calculators/car-loan-affordability-calculator-2026" },
      { title: "Retirement Savings", href: "/calculators/retirement-savings-calculator-2026" },
      { title: "College Savings", href: "/calculators/college-savings-calculator-2026" },
      { title: "Roth vs Traditional IRA", href: "/calculators/roth-vs-traditional-ira-calculator-2026" },
      { title: "401(k) Retirement", href: "/calculators/401k-retirement-calculator" },
      { title: "Roth IRA Growth", href: "/calculators/roth-ira-growth-calculator" },
      { title: "Hourly Wage US", href: "/calculators/hourly-wage-calculator-us" },
    ],
  },
  {
    title: "Merchant & Fees",
    links: [
      { title: "Stripe Fee Calculator", href: "/calculators/stripe-fee-merchant-calculator" },
      { title: "PayPal Fee Calculator", href: "/calculators/paypal-fee-calculator" },
      { title: "eBay Seller Fees", href: "/calculators/ebay-seller-fee-profit" },
      { title: "Amazon FBA Fees", href: "/calculators/amazon-fba-fee-calculator" },
      { title: "E-Commerce Margin", href: "/calculators/ecommerce-net-profit-margin" },
      { title: "Airbnb Host Profit", href: "/calculators/airbnb-host-net-income" },
      { title: "Rental Property ROI", href: "/calculators/rental-property-roi-calculator" },
      { title: "Etsy Fee", href: "/calculators/etsy-fee-calculator-2026" },
      { title: "Shopify Profit", href: "/calculators/shopify-profit-calculator-2026" },
      { title: "Amazon Seller Fee", href: "/calculators/amazon-seller-fee-calculator-2026" },
    ],
  },
  {
    title: "Personal Finance",
    links: [
      { title: "Car Loan Affordability", href: "/calculators/car-loan-affordability-calculator-2026" },
      { title: "Retirement Savings", href: "/calculators/retirement-savings-calculator-2026" },
      { title: "Credit Card Payoff", href: "/calculators/credit-card-payoff-calculator" },
      { title: "Student Loan Payoff", href: "/calculators/student-loan-payoff-calculator" },
      { title: "Home Affordability", href: "/calculators/home-affordability-calculator-2026" },
      { title: "Emergency Fund", href: "/calculators/emergency-fund-calculator" },
      { title: "Net Worth", href: "/calculators/net-worth-calculator" },
      { title: "Mortgage Refinance", href: "/calculators/mortgage-refinance-calculator-2026" },
      { title: "Loan Comparison", href: "/calculators/loan-comparison-calculator" },
      { title: "Savings Goal", href: "/calculators/savings-goal-calculator" },
      { title: "Inflation", href: "/calculators/inflation-calculator" },
      { title: "Cost of Living", href: "/calculators/cost-of-living-calculator" },
      { title: "Commission", href: "/calculators/commission-calculator" },
      { title: "Budget Calculator", href: "/calculators/budget-calculator" },
      { title: "Mortgage Calculator US", href: "/calculators/mortgage-calculator-us" },
      { title: "Amortization Schedule", href: "/calculators/amortization-calculator" },
      { title: "DTI Ratio", href: "/calculators/dti-ratio-calculator" },
    ],
  },
  {
    title: "Resources",
    links: [
      { title: "Blog & Guides", href: "/blog" },
      { title: "FAQ Help Desk", href: "/faq" },
      { title: "Gig Economy Tax Guide", href: "/tools/gig-economy-tax-guide" },
      { title: "About Us", href: "/about" },
      { title: "Contact", href: "/contact" },
    ],
  },
];

export const homeHighlights = [
  {
    title: "Instant calculator results",
    description: "Fast, mobile-first UI with no signup required so users can get numbers immediately.",
  },
  {
    title: "SEO-friendly finance pages",
    description: "Modern headings, schema markup, FAQ rich snippets, and internal linking for better Google visibility.",
  },
  {
    title: "Built for scaling",
    description: "Add new calculators and guides quickly with consistent metadata, layout, and category structure.",
  },
];

export const categoryHighlights = [
  { title: "Gig Economy Taxes", href: "/calculators/doordash-tax-estimator" },
  { title: "E-Commerce Profit", href: "/calculators/ecommerce-net-profit-margin" },
  { title: "Self-Employment Filing", href: "/calculators/california-1099-tax-calculator" },
  { title: "Payment Fees", href: "/calculators/stripe-fee-merchant-calculator" },
  { title: "Retirement Planning", href: "/calculators/solo-401k-contribution-calculator" },
];

export const blogHighlights = blogPosts.slice(0, 6);

export function getRelatedCalculators(currentHref, limit = 3) {
  if (!currentHref) return calculators.slice(0, limit);

  const current = calculators.find((calc) => calc.href === currentHref);
  if (!current) return calculators.slice(0, limit);

  const sameTag = calculators
    .filter((calc) => calc.tag === current.tag && calc.href !== currentHref)
    .slice(0, limit);

  if (sameTag.length >= limit) return sameTag;

  const fallback = calculators.filter((calc) => calc.href !== currentHref && !sameTag.includes(calc)).slice(0, limit - sameTag.length);
  return [...sameTag, ...fallback];
}

export function getTopCalculators(limit = 6) {
  return calculators.slice(0, limit);
}

export const metaDefaults = {
  title: "TheMetricApp — Free Financial Calculators & Finance Guides",
  description:
    "Free financial calculators, tax estimators, and business tools for freelancers, gig workers, sellers, and self-employed professionals. Accurate 2026 formulas, fast results, and actionable guidance.",
  keywords: [
    "financial calculators",
    "tax calculator",
    "self employment tax calculator",
    "gig economy tax calculator",
    "ecommerce fee calculator",
    "freelancer finance tools",
    "small business calculators",
  ],
};
